version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Installing Node Modules...
      - npm config -g set prefer-offline true
      - npm config -g set cache /root/.npm
      - npm config get cache
      - cd ${CODEBUILD_SRC_DIR}
      - npm install -g @nestjs/cli
      - npm i
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - npm run ebs-build
  post_build:
    commands:
      - echo Build completed on `date`
      - rm -r .git*
artifacts:
  files:
    - '**/*'
cache:
  paths:
    - /root/.npm/**/*
    - 'node_modules/**/*'
    - 'build/**/*'
