version: '3.1'

services:
  docker-mongo:
    image: mongo:latest
    container_name: docker-mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
        
volumes:
  db-data:
  mongodb_data_container: